services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://backend:3000
    volumes:
      - ./frontend:/app                  # Powiązanie lokalnego katalogu z katalogiem aplikacji
      - /app/node_modules                 # Oddzielny wolumen dla node_modules, aby uniknąć nadpisania
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  frontend_node_modules:
