name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEAMTAILOR_API_URL: ${{ secrets.API_URL }}
      TEAMTAILOR_API_VERSION: ${{ secrets.API_VERSION }}
      TEAMTAILOR_API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm run start:prod &
          sleep 5

      - name: Run tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
